import { useState, useEffect, useContext } from "react";
import axios from "axios";
import { AuthContext } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { useNavigate } from "react-router-dom";

function MfaSetup() {
  const { token, fetchUser } = useContext(AuthContext);
  const { showToast } = useToast();
  const navigate = useNavigate();

  const [qrCode, setQrCode] = useState(null);
  const [secret, setSecret] = useState(null);
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [verifying, setVerifying] = useState(false);

  useEffect(() => {
    if (token) {
      loadMfaSetup();
    }
  }, [token]);

  const loadMfaSetup = async () => {
    setLoading(true);
    try {
      const res = await axios.get("http://localhost:8081/api/auth/mfa/setup", {
        headers: { Authorization: `Bearer ${token}` }
      });
      setQrCode(res.data.qrCode);
      setSecret(res.data.secret);
    } catch (err) {
      console.error(err);
      showToast("Failed to load MFA setup.", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleEnableMfa = async (e) => {
    e.preventDefault();
    if (code.length !== 6) {
      showToast("Please enter a 6-digit code.", "error");
      return;
    }
    setVerifying(true);
    try {
      await axios.post("http://localhost:8081/api/auth/mfa/enable", 
        { secret, code },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      showToast("Two-Factor Authentication enabled successfully!", "success");
      fetchUser(); // Refresh user state
      // Go back to previous page or dashboard
      navigate(-1);
    } catch (err) {
      showToast(err.response?.data || "Invalid MFA code. Please try again.", "error");
    } finally {
      setVerifying(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h2 style={styles.title}>Enable Two-Factor Authentication</h2>
        
        {loading ? (
          <p style={styles.loadingText}>Loading setup...</p>
        ) : (
          <>
            <p style={styles.instruction}>
              1. Open <strong>Google Authenticator</strong> or <strong>Microsoft Authenticator</strong> app on your phone.
            </p>
            <p style={styles.instruction}>
              2. Scan the QR code below:
            </p>
            
            {qrCode && (
              <div style={styles.qrContainer}>
                <img src={qrCode} alt="MFA QR Code" style={styles.qrImage} />
              </div>
            )}

            <p style={styles.instruction}>
              3. Enter the 6-digit code generated by the app:
            </p>

            <form onSubmit={handleEnableMfa} style={styles.form}>
              <input
                type="text"
                maxLength="6"
                placeholder="000000"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                style={styles.input}
                className="focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                required
              />
              <button 
                type="submit" 
                style={styles.button}
                disabled={verifying}
                className="hover:shadow-md transition-all hover:bg-blue-700"
              >
                {verifying ? "Verifying..." : "Enable MFA"}
              </button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}

const styles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "linear-gradient(135deg, #f3f4f6, #e5e7eb)"
  },
  card: {
    background: "#fff",
    padding: "40px",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "450px",
    boxShadow: "0 10px 25px rgba(0,0,0,0.05)",
    border: "1px solid #f0f0f0"
  },
  title: {
    textAlign: "center",
    marginBottom: "20px",
    color: "#1f2937",
    fontWeight: "700",
    fontSize: "22px"
  },
  instruction: {
    color: "#4b5563",
    fontSize: "14px",
    marginBottom: "10px",
    lineHeight: "1.5"
  },
  qrContainer: {
    display: "flex",
    justifyContent: "center",
    margin: "20px 0",
    padding: "15px",
    background: "#f9fafb",
    borderRadius: "8px",
    border: "1px dashed #d1d5db"
  },
  qrImage: {
    width: "200px",
    height: "200px"
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    marginTop: "10px"
  },
  input: {
    padding: "12px",
    fontSize: "20px",
    textAlign: "center",
    letterSpacing: "4px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    width: "100%",
    backgroundColor: "#f9fafb",
    color: "#1f2937",
    fontWeight: "600"
  },
  button: {
    background: "#1d4ed8",
    color: "#fff",
    padding: "14px",
    border: "none",
    borderRadius: "6px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%"
  },
  loadingText: {
    textAlign: "center",
    color: "#6b7280"
  }
};

export default MfaSetup;
